### PR TITLE
Support non-default I2C masters

### PR DESCRIPTION
**Pull request by JamesWhitlock**
This PR adds support for non-default I2C masters #30. A TwoWire instance can now be optionally parsed into the contructor, e.g.

```
MPU6050 imu(Wire2)
```

Given all currently supported IMUs are I2C devices, I've put the TwoWire reference in I2CBase.

### CODE REVIEW

**Comment by JamesWhitlock** [comment]
Hold off merging this. I just realised this doesn’t work for the hybrid imus. I will move the reference out of base.

**Comment by JamesWhitlock** [comment]
> Hold off merging this. I just realised this doesn’t work for the hybrid imus. I will move the reference out of base.

Done

**Comment by LiquidCGS** [comment]
Hello, sorry for the wait but this does not build on IDE 1.8.19, I haven't tested it on 2.x but i don't expect it to build either

```
F_ICM20689.hpp: In constructor 'ICM20689::ICM20689(TwoWire&)':
F_ICM20689.hpp:87:53: error: no matching function for call to 'IMUBase::IMUBase()'
   87 |  explicit ICM20689(TwoWire& wire = Wire) : wire(wire) {};
```

and so on for pretty much every IMU.

**Comment by LiquidCGS** [comment]
Changing
`explicit ICM20689(TwoWire& wire = Wire) : wire(wire) {};`
to 
`explicit ICM20689(TwoWire& wire = Wire) : IMUBase(wire), wire(wire) {};`
in the constructor seems to do the trick for the IMU's, and changing 
`explicit ICM20689_AK8975(TwoWire& wire = Wire) : IMU(wire), MAG(wire) {};`
to
`explicit ICM20689_AK8975(TwoWire& wire = Wire) : IMUBase(wire), IMU(wire), MAG(wire) {}`
in the hybrid IMU's also seems to do the trick.

However I don't have anything on hand that has multiple hardware i2c ports to test this with, I tried compiling it with an ESP32 as the board and it seems to take both "Wire" and "Wire1" in the constructor just fine but I don't have one handy to test with

**Comment by JamesWhitlock** [comment]
Hi, I tested compilation of all IMUs on 2.3.3. A quick google suggests that the gcc version is the same between versions, so I'm not sure why it's failing. I'm just installing 1.8.9.

**Comment by JamesWhitlock** [comment]
Right, my setup was wrong - sorry for the trouble. I'll just check the fix and push it when done.

**Comment by LiquidCGS** [comment]
No worries!

**Comment by JamesWhitlock** [comment]
I pushed a fix, I removed the TwoWire reference and constructor out of the IMUBase class so that it remains as a pure interface. This makes sense for the IMU and compass combos and for non-I2C IMUs in future (e.g. SPI).

**Comment by LiquidCGS** [comment]
Looks and runs well now! I'll push an update to the arduino library manager version soon-ish after I do some cleanup
